language: node_js
node_js:
  - 12
before_script:
  - cd backend-express
  - yarn install
  - cd ../frontend-next
  - yarn install
script:
  - cd ../backend-express
  - yarn test
  - cd ../frontend-express
  - yarn test
