# for server development purpose only.
# please use docker-compose on top level for production deploy
# please use docker stack deploy instead of docker-compose up. for ease in production.
version: "3.7"
services:
  app-express:
    image: cached-backend-dev:latest
    environment:
      # - NODE_ENV=development # the NODE_ENV is predefined from npm script
      - PORT=4500
      - REDIS_URL=redis://db-redis
      - MONGO_URI=mongodb://db-mongo:27017
    volumes:
      - ./:/home/node/app
      - app-express:/home/node/app/node_modules
    ports:
      - 4500:4500
    networks:
      - overlay
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  db-redis: # connect via redis://db-redis:6379
    image: redis:5.0.7-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - overlay

  db-mongo: # connect via mongo
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    networks:
      - overlay
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example

networks:
  overlay:
    driver: overlay
volumes:
  mongodb:
  app-express: